version: '3.7'

services:
  db-ms-auth:
    image: postgres:13
    container_name: postgres_db_auth
    environment:
      POSTGRES_DB: ${POSTGRES_DB_AUTH}
      POSTGRES_USER: ${POSTGRES_USER_AUTH}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_AUTH}
    ports:
      - "5433:5432"
    networks:
      - main-network
    volumes:
      - db-auth:/var/lib/postgresql/data

  db-ms-franchise:
    image: postgres:13
    container_name: postgres_db_franchise
    environment:
      POSTGRES_DB: ${POSTGRES_DB_FRAN}
      POSTGRES_USER: ${POSTGRES_USER_FRAN}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_FRAN}
    ports:
      - "5434:5432"
    networks:
      - main-network
    volumes:
      - db-fran:/var/lib/postgresql/data

  ms-auth:
    build:
      context: ./ms-auth
      dockerfile: Dockerfile
    container_name: ms-auth
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - db-ms-auth
    ports:
      - "7071:8080"
    networks:
      - main-network

  ms-franchise:
    build:
      context: ./ms-franchise
      dockerfile: Dockerfile
    container_name: ms-franchise
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - db-ms-franchise
    ports:
      - "7072:8080"
    networks:
      - main-network


  kong-dbless:
    image: kong:3.4.2
    container_name: kong-dbless
    volumes:
      - ./kong.yml:/kong/declarative/kong.yml
    environment:
      KONG_DATABASE: off
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
      KONG_ADMIN_GUI_URL: "http://localhost:8002"
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    networks:
      - main-network

networks:
  main-network:
    driver: bridge

volumes:
  db-auth:
  db-fran:
